apiVersion: v1
kind: Service
metadata:
  name: svc-vehicle
  labels:
    app: svc-vehicle
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32703
  selector:
    app: pod-vehicle-application