spring:
  application:
    name: ${APP_NAME:vehicle-application}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/user-management}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/realms/user-management/protocol/openid-connect/certs}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}
  datasource:
    url: ${URL_DATABASE:jdbc:mysql://mysql-db:3306/vehicle}
    username: ${USER_DATABASE:user}
    password: ${PASSWORD_DATABASE:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

user-api:
  url: ${USER_ENDPOINT:http://localhost:8082}

server:
  port: ${APP_PORT:80}
