apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-vehicle
  labels:
    app: mysql-db-vehicle
spec:
  containers:
    - name: mysql
      image: mysql:8
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-user
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-configmap-vehicle-application
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-configmap-vehicle-application
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-user
              key: MYSQL_PASSWORD
      ports:
        - containerPort: 3306