apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-vehicle-application
data:
  APP_NAME: "vehicle-application"
  ISSUER_URI: "http://keycloak-service:8081/realms/user-management"
  JWK_SET_URI: "http://keycloak-service:8081/realms/user-management/protocol/openid-connect/certs"
  DDL_AUTO: "create-drop"
  SHOW_SQL: "true"
  URL_DATABASE: "jdbc:mysql://svc-mysql-db-vehicles:3306/vehicles"
  USER_DATABASE: "user"
#  USER_ENDPOINT: "http://user-service:8080/users"
  USER_ENDPOINT: "http://abcefc404ab5641d689b7d120b5bfa19-2111440822.us-east-1.elb.amazonaws.com/users"
  APP_PORT: "80"
  MYSQL_DATABASE: "vehicles"
  MYSQL_USER: "user"