name: Cria o PR para a main

on:
  push:
    branches:
      - release

jobs:
  deploy-eks:
    name: "Deploy no cluster EKS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: echo 'Fake step to deploy EKS Cluster'

  pr-to-main-branch:
    name: "Cria PR para main branch"
    runs-on: ubuntu-latest
    needs:
      - deploy-eks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Configure Git
        run: |
          git config --global user.email "gtbarbosa@live.com"
          git config --global user.name "gustavo-dev"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verificar se já existe PR aberto para main
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base main --head $(echo "${{ github.ref }}" | sed 's/refs\/heads\///') --json url --jq 'length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.PR_EXISTS == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          gh pr create --base main --head $BRANCH_NAME --title "PR da branch: $BRANCH_NAME para a branch main" --body "PR criado automaticamente. From $BRANCH_NAME to main."
